### ISSUE TITLE
java.lang.IllegalArgumentException: Unsupported class file major version 62

### ISSUE THREAD

**Issue by ParzivalWolfram** [ecx86/jda#73]
Running JDA on Debian Sid under `openjdk-18-jre`.  Opening any JAR file will show the list of classes, but claim that the class file major is unsupported, including those of the same version as the JRE. Am I missing something?

**Comment by tnais** [comment]
Happens also using 

openjdk 21.0.4 2024-07-16
OpenJDK Runtime Environment (build 21.0.4+7-Ubuntu-1ubuntu224.04)
OpenJDK 64-Bit Server VM (build 21.0.4+7-Ubuntu-1ubuntu224.04, mixed mode, sharing)

and when the major version is 61

Stack trace:

Error while decompiling NFDCSMainGUI.class:
java.lang.IllegalArgumentException: Unsupported class file major version 61
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:195)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:176)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:162)
	at club.bytecode.the.jda.util.BytecodeUtils.loadClass(BytecodeUtils.java:30)
	at club.bytecode.the.jda.FileContainer.loadClassFile(FileContainer.java:31)
	at club.bytecode.the.jda.gui.fileviewer.DecompileThread.run(DecompileThread.java:41)
